### ISSUE TITLE
Missing `/data` folder

### ISSUE THREAD

**Issue by matescharnitzky** [fonnesbeck/bayes_course_2023#1]
Hi Chris,
I'm looking forward to having the training next week. I started looking into the pre-course material, and there is a reference to the `/data` folder. 

<img width="998" alt="image" src="https://github.com/fonnesbeck/bayes_course_2023/assets/8216624/8302d775-8182-414e-976b-a92d1ce0bcda">

Was it meant to be pushed to the repo or are we supposed to download it from a public source?
Thank you for the clarification!

**Comment by fonnesbeck** [comment]
Sorry, just saw this now! The data should be there now.
